# Generated by Django 3.1.7 on 2023-06-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_provider'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='domains',
            field=models.ManyToManyField(to='core.Domain'),
        ),
    ]
