# Generated by Django 3.1.7 on 2021-04-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_auto_20210404_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
