# Generated by Django 3.1.7 on 2021-04-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.TextField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cpf',
            field=models.TextField(default='', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='fiscal_note',
            field=models.TextField(default=None, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='installments',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
