# Generated by Django 3.1.7 on 2023-06-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0007_cob'),
    ]

    operations = [
        migrations.AddField(
            model_name='cob',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cob',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cob',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
